CREATE TABLE IF NOT EXISTS data.pokedex (
  pokemonId SMALLINT NOT NULL,
  name VARCHAR(32) NOT NULL,
  frenchName VARCHAR(32) NOT NULL,
  type1 VARCHAR(32) NOT NULL,
  type2 VARCHAR(32),
  hp SMALLINT NOT NULL,
  attack SMALLINT NOT NULL,
  defense SMALLINT NOT NULL,
  spAttack SMALLINT NOT NULL,
  spDefense SMALLINT NOT NULL,
  speed SMALLINT NOT NULL,
  species VARCHAR(64) NOT NULL,
  description VARCHAR(512) NOT NULL,
  evIds VARCHAR(64),
  evLevel VARCHAR(64),
  height FLOAT(6, 1) NOT NULL,
  weight FLOAT(6, 1) NOT NULL,
  egg1 VARCHAR(32) NOT NULL,
  egg2 VARCHAR(32),
  ability1 VARCHAR(32),
  ability2 VARCHAR(32),
  ability3 VARCHAR(32),
  pctMale DECIMAL(4, 1),
  gender VARCHAR(32) NOT NULL,
  frequency SMALLINT NOT NULL,
  gen VARCHAR(32) NOT NULL,
  genInt SMALLINT NOT NULL
);
