"use strict";

function getSymb(code) {
  if(code == '200') return '⛈️';
  if(code == '201') return '⛈️';
  if(code == '202') return '⛈️';
  if(code == '210') return '🌩️';
  if(code == '211') return '🌩️';
  if(code == '212') return '🌩️';
  if(code == '221') return '🌩️';
  if(code == '230') return '⛈️';
  if(code == '231') return '⛈️';
  if(code == '232') return '⛈️';
  if(code == '300') return '🌧️';
  if(code == '301') return '🌧️';
  if(code == '302') return '🌧️';
  if(code == '310') return '🌧️';
  if(code == '311') return '🌧️';
  if(code == '312') return '🌧️';
  if(code == '313') return '🌧️';
  if(code == '314') return '🌧️';
  if(code == '321') return '🌧️';
  if(code == '500') return '🌧️';
  if(code == '501') return '🌧️';
  if(code == '502') return '🌧️';
  if(code == '503') return '🌧️';
  if(code == '504') return '🌧️';
  if(code == '511') return '🌧️';
  if(code == '520') return '🌧️';
  if(code == '521') return '🌧️';
  if(code == '522') return '🌧️';
  if(code == '531') return '🌧️';
  if(code == '600') return '🌨️';
  if(code == '601') return '🌨️';
  if(code == '602') return '🌨️';
  if(code == '611') return '🌨️';
  if(code == '612') return '🌨️';
  if(code == '613') return '🌨️';
  if(code == '615') return '🌨️';
  if(code == '616') return '🌨️';
  if(code == '620') return '🌨️';
  if(code == '621') return '🌨️';
  if(code == '622') return '🌨️';
  if(code == '701') return '🌫️';
  if(code == '711') return '🌫️';
  if(code == '721') return '🌫️';
  if(code == '731') return '🌫️';
  if(code == '741') return '🌫️';
  if(code == '751') return '🌫️';
  if(code == '761') return '🌫️';
  if(code == '762') return '🌫️';
  if(code == '771') return '🌫️';
  if(code == '781') return '🌪️';
  if(code == '800') return '☀️';
  if(code == '801') return '🌤️';
  if(code == '802') return '⛅';
  if(code == '803') return '🌥️';
  if(code == '804') return '☁️';
  return '❔';
}

module.exports = { getSymb };
